version: 1.0
sections:
  - name: Formación académica y complementaria
    max_score: 450
  - name: Cargos
    max_score: 500
  - name: Ciencia y Tecnología
    max_score: 500
  - name: Producciones y servicios
    max_score: 350
  - name: Otros antecedentes
    max_score: 200
